(function(window) {
    var config = {
        'head_displayId': 'head_display',
        'feedId': 'feed',
        'max_news_per_site': 2,
        // 'input_data2': { "count": 6, "data": [{ "priority": 1, "url": "http://realtytimes.com/", "type": "mainpage" }, { "priority": 2, "url": "http://timesofindia.indiatimes.com/", "type": "mainpage" }, { "priority": 4, "url": "http://page2rss.com/5a11ae68559796f395886bd54bd108ee", "type": "rss" }, { "priority": 5, "url": "http://timesofindia.feedsportal.com/c/33039/f/533922/index.rss", "type": "rss" }, { "priority": 6, "url": "http://timesofindia.feedsportal.com/c/33039/f/533925/index.rss", "type": "rss" }, { "priority": 7, "url": "http://timesofindia.feedsportal.com/c/33039/f/533924/index.rss", "type": "rss" }] },
        // 'input_data2': { "count": 1, "data": [{ "priority": 1, "url": "http://feeds2.feedburner.com/rismedia/lgnb", "type": "rss" }, ] },
        'input_data2': { "count": 1, "data": [{ "priority": 0, "url": "http://www.hindustantimes.com/", "type": "mainpage" }, { "priority": 1, "url": "http://www.cnbc.com/id/10000115/device/rss/rss.html", "type": "rss" }, { "priority": 2, "url": "http://feeds.feedburner.com/NDTV-Business", "type": "rss" }, { "priority": 3, "url": "http://feeds.feedburner.com/NDTV-Business", "type": "rss" }, { "priority": 4, "url": "http://realty.economictimes.indiatimes.com/rss/topstories", "type": "rss" }, { "priority": 5, "url": "http://realty.economictimes.indiatimes.com/rss/recentstories", "type": "rss" }, { "priority": 6, "url": "http://realty.economictimes.indiatimes.com/rss/residential", "type": "rss" }, { "priority": 7, "url": "http://realty.economictimes.indiatimes.com/rss/commercial", "type": "rss" }, { "priority": 8, "url": "http://realty.economictimes.indiatimes.com/rss/retail", "type": "rss" }, { "priority": 9, "url": "http://realty.economictimes.indiatimes.com/rss/hospitality", "type": "rss" }, { "priority": 10, "url": "http://realty.economictimes.indiatimes.com/rss/regulatory", "type": "rss" }, { "priority": 11, "url": "http://realty.economictimes.indiatimes.com/rss/industry", "type": "rss" }, { "priority": 12, "url": "http://realty.economictimes.indiatimes.com/rss/technology", "type": "rss" }, { "priority": 13, "url": "http://realty.economictimes.indiatimes.com/rss/allied-industries", "type": "rss" }, { "priority": 14, "url": "http://feeds2.feedburner.com/rismedia/lgnb", "type": "rss" }, { "priority": 15, "url": "http://feeds.feedburner.com/RISMedia", "type": "rss" }, { "priority": 16, "url": "http://feeds2.feedburner.com/RismediaBusinessDevelopment", "type": "rss" }, { "priority": 17, "url": "http://feeds2.feedburner.com/RismediaCoaching", "type": "rss" }, { "priority": 18, "url": "http://feeds.feedburner.com/RismediaFinanceAndEconomy", "type": "rss" }, { "priority": 19, "url": "http://feeds2.feedburner.com/RismediaMarketing", "type": "rss" }, { "priority": 20, "url": "http://feeds2.feedburner.com/RismediaTechnology", "type": "rss" }, { "priority": 21, "url": "http://feeds2.feedburner.com/RismediaTodaysHomeSpunWisdom", "type": "rss" }, { "priority": 22, "url": "http://feeds2.feedburner.com/RismediaTodaysMarketplace", "type": "rss" }, { "priority": 23, "url": "http://feeds2.feedburner.com/RismediaTodaysTopStory", "type": "rss" }, { "priority": 24, "url": "http://feeds2.feedburner.com/RismediaConsumerNewsAndAdvice", "type": "rss" }, { "priority": 25, "url": "http://feeds2.feedburner.com/RismediaHomeBuying101", "type": "rss" }, { "priority": 26, "url": "http://feeds2.feedburner.com/RismediaTodaysHomeSpunWisdom", "type": "rss" }, { "priority": 27, "url": "http://feeds2.feedburner.com/RismediaTodaysTopStory-Consumer", "type": "rss" }, { "priority": 28, "url": "http://www.propertywire.com/rss-feed/news/", "type": "rss" }, { "priority": 29, "url": "http://www.jdsupra.com/resources/syndication/docsRSSfeed.aspx?ftype=RealEstate", "type": "rss" }] },
        'words_to_check': ["sanjay", "smriti", "jaitley", "budget", "solutions", "cement", "save", "energy", "material"],
        'timeout': 100000000000
    };

    window.config = config;

})(window);
